### PR TITLE
Grid function fix

### PR DESCRIPTION
**Pull request by ekwessel**
**Please ignore the earlier commits, and _only pay attention to the most recent commit, 687e28a_. This is a one-line change**.

Problem:
cactus_grid_functions.py fails on all the grid data I have tried to read. The problem is reading strings from some of the h5py output: at a certain point, .decode() is called on numpy arrays, but the types of the arrays aren't always correct. In my files, these read as single-byte integer arrays (type '|i1'), which have no decode() method. The solution seems to be to call .tostring() on them first, which changes their type (the name is a misnomer), and then decode() works after that, as in this basic example:
>>> arr = np.array([65, 65, 65, 66], dtype='|i1') # 'AAAB'
>>> arr[()].decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'decode'
>>> arr[()].tostring().decode()
'AAAB'

I have added this to the code, and all the unit tests seem to work, but I can't easily check whether this change causes trouble for grid output from the normal Einstein toolkit thorns, so that should be checked before adding this to the main repo.

### CODE REVIEW

**Comment by Sbozzolo** [comment]
Thanks for this report. I am perplexed: the lines you changed only have to do with reading the parameters stored in the hdf5 data, which should be strings. If you can send me a small examples of where the code fails, I can see what is the problem, because maybe the root is elsewhere and that routine is called when it should not be.

**Comment by Sbozzolo** [comment]
In Einstein Toolkit files
`f["Parameters and Global Attributes"]["All Parameters"}` is `<HDF5 dataset "All Parameters": shape (), type "|S5402">`,
which I interpret as being a string (with fixed length).

**Comment by ekwessel** [comment]
Interesting, it seems to me that this may only be a problem for the IL code. In diagnosing the problem, added the following line:
`print(f["Parameters and Global Attributes"]["All Parameters"])`
Which, for my h5 files, resulted in:
`<HDF5 dataset "All Parameters": shape (6668,), type "|i1">`
Because the types were different, I got an error, but adding .tostring() seemed to fix everything.
If you'd like I can give you access to one of my h5 files, they are about 115MB (I'm not experienced with modifying HDF5 files, so I don't know how to cut out iterations to make them smaller)

**Comment by Sbozzolo** [comment]
I looked into this and I found that this is a bug in versions of Carpet before 2012. The fix was introduced with this commit:
https://bitbucket.org/eschnett/carpet/commits/d42e4e1aabf6b7a069701dd779d0b3291bc54012

I am not sure if we should add the fix you are proposing to this code or only keep it in the IL-compatible one...

**Comment by ekwessel** [comment]
Wow, thanks for finding that out!
This doesn't seem like something that needs to be supported by PostCactus then, because I can't think of any good reason for someone to cling to such an old version of Carpet, so I doubt there are many .h5 files out there that would cause this issue. I'm going to go ahead and close the request 👍

**Pull request closed without merging**
